/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) COUNT([TRADE_ACTION_ID]) AS QUANT_TA
	  ,FORMAT(SUM((MONEY_INVESTMENT - TRADER_INCOME)), '#,#') AS Site_Revenue
	  ,CONVERT(VARCHAR(15),CLOSE_TIME, 120)+'0' AS '10min'
	  ,SUM((MONEY_INVESTMENT - TRADER_INCOME) * ISNULL(EXCH_RATE, 1)) AS USD
	  ,SUM(MONEY_INVESTMENT * ISNULL(EXCH_RATE, 1)) AS USD_VOLUME
	  ,SUM((MONEY_INVESTMENT - TRADER_INCOME) * ISNULL(EXCH_RATE, 1))/SUM(MONEY_INVESTMENT * ISNULL(EXCH_RATE, 1)) AS USD_MARGIN
  FROM [MarketsPulse].[dbo].[TFC_TRADE_ACTIONS] ta
  with (index(IX_TFC_TRADE_ACTIONS_CLOSE_TIME))
  LEFT JOIN T_CURRENCY_EXCH_RATE c ON ta.CURRENCY_ID = c.SRC_CODE AND DEST_CODE = '840'
  WHERE CLOSE_TIME > '2022-08-01'
  GROUP BY(CONVERT(VARCHAR(15),CLOSE_TIME, 120))
  ORDER BY 3
  